{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNT2DJzJnwUdE+G54MVj/us",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/anacaetano02/Projetos-Redes-Neurais/blob/main/Projeto_1_MLP_src_.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 5,
      "metadata": {
        "id": "RXAyLZWSyKKQ"
      },
      "outputs": [],
      "source": [
        "import os\n",
        "os.makedirs('src', exist_ok=True)"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "%%writefile src/model.py\n",
        "\n",
        "\"\"\"\n",
        "model.py — Definições das arquiteturas MLP para classificação e regressão.\n",
        "Dataset: Lending Club (Kaggle)\n",
        "Autor: MBA Engenharia de IA\n",
        "\"\"\"\n",
        "\n",
        "import torch\n",
        "import torch.nn as nn\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------------------------\n",
        "# Bloco auxiliar: camada densa com normalização e ativação opcionais\n",
        "# ---------------------------------------------------------------------------\n",
        "class CamadaDensa(nn.Module):\n",
        "    \"\"\"\n",
        "    Bloco reutilizável: Linear → (Norm) → Ativação → (Dropout).\n",
        "\n",
        "    Parâmetros\n",
        "    ----------\n",
        "    entrada : int\n",
        "        Dimensão de entrada.\n",
        "    saida : int\n",
        "        Dimensão de saída.\n",
        "    ativacao : nn.Module\n",
        "        Instância da função de ativação (ex: nn.ReLU()).\n",
        "    norm : str ou None\n",
        "        'batch' para BatchNorm1d, 'layer' para LayerNorm, None para nenhuma.\n",
        "    dropout_p : float\n",
        "        Probabilidade de dropout (0.0 = desativado).\n",
        "    \"\"\"\n",
        "\n",
        "    def __init__(self, entrada: int, saida: int,\n",
        "                 ativacao: nn.Module = None,\n",
        "                 norm: str = None,\n",
        "                 dropout_p: float = 0.0):\n",
        "        super().__init__()\n",
        "\n",
        "        camadas = [nn.Linear(entrada, saida)]\n",
        "\n",
        "        if norm == 'batch':\n",
        "            camadas.append(nn.BatchNorm1d(saida))\n",
        "        elif norm == 'layer':\n",
        "            camadas.append(nn.LayerNorm(saida))\n",
        "\n",
        "        if ativacao is not None:\n",
        "            camadas.append(ativacao)\n",
        "\n",
        "        if dropout_p > 0.0:\n",
        "            camadas.append(nn.Dropout(p=dropout_p))\n",
        "\n",
        "        self.bloco = nn.Sequential(*camadas)\n",
        "\n",
        "    def forward(self, x: torch.Tensor) -> torch.Tensor:\n",
        "        return self.bloco(x)\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------------------------\n",
        "# MLP para Classificação Binária\n",
        "# ---------------------------------------------------------------------------\n",
        "class MLPClassificador(nn.Module):\n",
        "    \"\"\"\n",
        "    MLP para classificação binária (Lending Club: Fully Paid vs Charged Off).\n",
        "\n",
        "    Arquitetura justificada:\n",
        "    - Profundidade 3 camadas ocultas: suficiente para capturar interações\n",
        "      não-lineares entre features financeiras (dti, fico, int_rate, etc.)\n",
        "      sem risco excessivo de overfitting para ~350k amostras.\n",
        "    - Largura decrescente (256→128→64): pirâmide de compressão progressiva\n",
        "      que força representações cada vez mais abstratas do risco de crédito.\n",
        "\n",
        "    Parâmetros\n",
        "    ----------\n",
        "    n_features : int\n",
        "        Número de features de entrada após pré-processamento.\n",
        "    camadas_ocultas : list[int]\n",
        "        Lista com o tamanho de cada camada oculta.\n",
        "        Padrão: [256, 128, 64]\n",
        "    ativacao : str\n",
        "        'relu', 'tanh', 'leaky_relu', 'elu' ou 'selu'.\n",
        "    norm : str ou None\n",
        "        'batch', 'layer' ou None.\n",
        "    dropout_p : float\n",
        "        Probabilidade de dropout nas camadas ocultas.\n",
        "    \"\"\"\n",
        "\n",
        "    ATIVACOES = {\n",
        "        'relu':       nn.ReLU(),\n",
        "        'tanh':       nn.Tanh(),\n",
        "        'leaky_relu': nn.LeakyReLU(negative_slope=0.01),\n",
        "        'elu':        nn.ELU(),\n",
        "        'selu':       nn.SELU(),\n",
        "    }\n",
        "\n",
        "    def __init__(self,\n",
        "                 n_features: int,\n",
        "                 camadas_ocultas: list = None,\n",
        "                 ativacao: str = 'relu',\n",
        "                 norm: str = None,\n",
        "                 dropout_p: float = 0.0):\n",
        "        super().__init__()\n",
        "\n",
        "        if camadas_ocultas is None:\n",
        "            camadas_ocultas = [256, 128, 64]\n",
        "\n",
        "        if ativacao not in self.ATIVACOES:\n",
        "            raise ValueError(f\"Ativação '{ativacao}' não suportada. \"\n",
        "                             f\"Escolha: {list(self.ATIVACOES.keys())}\")\n",
        "\n",
        "        # Constrói as camadas ocultas dinamicamente\n",
        "        blocos = []\n",
        "        dim_entrada = n_features\n",
        "        for dim_saida in camadas_ocultas:\n",
        "            # Cria nova instância da ativação para cada bloco (evita estado compartilhado)\n",
        "            ativ = self._nova_ativacao(ativacao)\n",
        "            blocos.append(CamadaDensa(dim_entrada, dim_saida,\n",
        "                                      ativacao=ativ,\n",
        "                                      norm=norm,\n",
        "                                      dropout_p=dropout_p))\n",
        "            dim_entrada = dim_saida\n",
        "\n",
        "        self.camadas_ocultas = nn.Sequential(*blocos)\n",
        "\n",
        "        # Camada de saída: sem ativação (BCEWithLogitsLoss espera logits)\n",
        "        self.saida = nn.Linear(dim_entrada, 1)\n",
        "\n",
        "        # Salva hiperparâmetros para inspeção\n",
        "        self.n_features = n_features\n",
        "        self.config_ativacao = ativacao\n",
        "        self.config_norm = norm\n",
        "        self.config_dropout = dropout_p\n",
        "\n",
        "    def _nova_ativacao(self, nome: str) -> nn.Module:\n",
        "        \"\"\"Retorna nova instância para evitar reutilização de estado.\"\"\"\n",
        "        mapa = {\n",
        "            'relu':       nn.ReLU(),\n",
        "            'tanh':       nn.Tanh(),\n",
        "            'leaky_relu': nn.LeakyReLU(negative_slope=0.01),\n",
        "            'elu':        nn.ELU(),\n",
        "            'selu':       nn.SELU(),\n",
        "        }\n",
        "        return mapa[nome]\n",
        "\n",
        "    def forward(self, x: torch.Tensor) -> torch.Tensor:\n",
        "        \"\"\"\n",
        "        Forward pass.\n",
        "\n",
        "        Entrada: (batch, n_features)\n",
        "        Saída:   (batch, 1) — logit não normalizado\n",
        "        \"\"\"\n",
        "        x = self.camadas_ocultas(x)\n",
        "        return self.saida(x)\n",
        "\n",
        "    def resumo(self) -> str:\n",
        "        \"\"\"Retorna string descritiva da arquitetura.\"\"\"\n",
        "        total_params = sum(p.numel() for p in self.parameters() if p.requires_grad)\n",
        "        return (f\"MLPClassificador | Ativação: {self.config_ativacao} | \"\n",
        "                f\"Norm: {self.config_norm} | Dropout: {self.config_dropout} | \"\n",
        "                f\"Parâmetros treináveis: {total_params:,}\")\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------------------------\n",
        "# MLP para Regressão\n",
        "# ---------------------------------------------------------------------------\n",
        "class MLPRegressor(nn.Module):\n",
        "    \"\"\"\n",
        "    MLP para regressão: prediz int_rate (taxa de juros) como variável contínua.\n",
        "\n",
        "    Arquitetura:\n",
        "    - Mesma lógica da pirâmide do classificador, mas a saída é um escalar\n",
        "      contínuo (sem sigmoid/softmax).\n",
        "    - Loss: MSELoss | Métricas: MAE, RMSE, R²\n",
        "\n",
        "    Parâmetros\n",
        "    ----------\n",
        "    n_features : int\n",
        "        Número de features de entrada (mesmo conjunto do classificador,\n",
        "        mas sem int_rate que agora é o target).\n",
        "    camadas_ocultas : list[int]\n",
        "        Padrão: [256, 128, 64]\n",
        "    ativacao : str\n",
        "        Mesmas opções do MLPClassificador.\n",
        "    norm : str ou None\n",
        "        'batch', 'layer' ou None.\n",
        "    dropout_p : float\n",
        "        Probabilidade de dropout.\n",
        "    \"\"\"\n",
        "\n",
        "    def __init__(self,\n",
        "                 n_features: int,\n",
        "                 camadas_ocultas: list = None,\n",
        "                 ativacao: str = 'relu',\n",
        "                 norm: str = None,\n",
        "                 dropout_p: float = 0.0):\n",
        "        super().__init__()\n",
        "\n",
        "        if camadas_ocultas is None:\n",
        "            camadas_ocultas = [256, 128, 64]\n",
        "\n",
        "        blocos = []\n",
        "        dim_entrada = n_features\n",
        "        for dim_saida in camadas_ocultas:\n",
        "            ativ = self._nova_ativacao(ativacao)\n",
        "            blocos.append(CamadaDensa(dim_entrada, dim_saida,\n",
        "                                      ativacao=ativ,\n",
        "                                      norm=norm,\n",
        "                                      dropout_p=dropout_p))\n",
        "            dim_entrada = dim_saida\n",
        "\n",
        "        self.camadas_ocultas = nn.Sequential(*blocos)\n",
        "\n",
        "        # Saída escalar contínua (sem ativação)\n",
        "        self.saida = nn.Linear(dim_entrada, 1)\n",
        "\n",
        "        self.n_features = n_features\n",
        "        self.config_ativacao = ativacao\n",
        "        self.config_norm = norm\n",
        "        self.config_dropout = dropout_p\n",
        "\n",
        "    def _nova_ativacao(self, nome: str) -> nn.Module:\n",
        "        mapa = {\n",
        "            'relu':       nn.ReLU(),\n",
        "            'tanh':       nn.Tanh(),\n",
        "            'leaky_relu': nn.LeakyReLU(negative_slope=0.01),\n",
        "            'elu':        nn.ELU(),\n",
        "            'selu':       nn.SELU(),\n",
        "        }\n",
        "        return mapa[nome]\n",
        "\n",
        "    def forward(self, x: torch.Tensor) -> torch.Tensor:\n",
        "        \"\"\"\n",
        "        Forward pass.\n",
        "\n",
        "        Entrada: (batch, n_features)\n",
        "        Saída:   (batch, 1) — valor contínuo (int_rate previsto)\n",
        "        \"\"\"\n",
        "        x = self.camadas_ocultas(x)\n",
        "        return self.saida(x)\n",
        "\n",
        "    def resumo(self) -> str:\n",
        "        total_params = sum(p.numel() for p in self.parameters() if p.requires_grad)\n",
        "        return (f\"MLPRegressor | Ativação: {self.config_ativacao} | \"\n",
        "                f\"Norm: {self.config_norm} | Dropout: {self.config_dropout} | \"\n",
        "                f\"Parâmetros treináveis: {total_params:,}\")\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------------------------\n",
        "# Funções de inicialização de pesos\n",
        "# ---------------------------------------------------------------------------\n",
        "def inicializar_pesos(modelo: nn.Module, metodo: str = 'xavier_uniform') -> None:\n",
        "    \"\"\"\n",
        "    Aplica inicialização de pesos a todas as camadas Linear do modelo.\n",
        "\n",
        "    Parâmetros\n",
        "    ----------\n",
        "    modelo : nn.Module\n",
        "        Modelo a ser inicializado.\n",
        "    metodo : str\n",
        "        'xavier_uniform'  — Xavier/Glorot uniforme (bom para tanh/sigmoid)\n",
        "        'xavier_normal'   — Xavier/Glorot normal\n",
        "        'he_uniform'      — He uniforme (bom para ReLU e variantes)\n",
        "        'he_normal'       — He normal (padrão do PyTorch para ReLU)\n",
        "        'padrao'          — Mantém a inicialização padrão do PyTorch (Kaiming uniform)\n",
        "    \"\"\"\n",
        "    if metodo == 'padrao':\n",
        "        # Não faz nada — mantém o padrão do PyTorch\n",
        "        return\n",
        "\n",
        "    for modulo in modelo.modules():\n",
        "        if isinstance(modulo, nn.Linear):\n",
        "            if metodo == 'xavier_uniform':\n",
        "                nn.init.xavier_uniform_(modulo.weight)\n",
        "            elif metodo == 'xavier_normal':\n",
        "                nn.init.xavier_normal_(modulo.weight)\n",
        "            elif metodo == 'he_uniform':\n",
        "                nn.init.kaiming_uniform_(modulo.weight, nonlinearity='relu')\n",
        "            elif metodo == 'he_normal':\n",
        "                nn.init.kaiming_normal_(modulo.weight, nonlinearity='relu')\n",
        "            else:\n",
        "                raise ValueError(f\"Método '{metodo}' não reconhecido.\")\n",
        "\n",
        "            if modulo.bias is not None:\n",
        "                nn.init.zeros_(modulo.bias)\n",
        "\n",
        "\n",
        "def inspecionar_pesos(modelo: nn.Module) -> None:\n",
        "    \"\"\"\n",
        "    Imprime estatísticas dos pesos de cada camada Linear.\n",
        "    Útil para comparar distribuições antes/depois da inicialização.\n",
        "    \"\"\"\n",
        "    print(f\"\\n{'='*60}\")\n",
        "    print(f\"{'Camada':<30} {'Média':>10} {'Std':>10} {'Min':>10} {'Max':>10}\")\n",
        "    print(f\"{'='*60}\")\n",
        "    for nome, param in modelo.named_parameters():\n",
        "        if 'weight' in nome:\n",
        "            dados = param.data\n",
        "            print(f\"{nome:<30} {dados.mean().item():>10.4f} \"\n",
        "                  f\"{dados.std().item():>10.4f} \"\n",
        "                  f\"{dados.min().item():>10.4f} \"\n",
        "                  f\"{dados.max().item():>10.4f}\")\n",
        "    print(f\"{'='*60}\\n\")\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "HTqiAUuGyYsU",
        "outputId": "dc9aaead-a635-49ce-be83-296461fb32b4"
      },
      "execution_count": 6,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Overwriting src/model.py\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "%%writefile src/training.py\n",
        "\n",
        "\"\"\"\n",
        "training.py — Training loop, validação por época, checkpointing e LR scheduling.\n",
        "Dataset: Lending Club (Kaggle)\n",
        "Autor: MBA Engenharia de IA\n",
        "\"\"\"\n",
        "\n",
        "import os\n",
        "import time\n",
        "import torch\n",
        "import torch.nn as nn\n",
        "from torch.utils.data import DataLoader\n",
        "from torch.utils.tensorboard import SummaryWriter\n",
        "from typing import Dict, List, Tuple, Optional\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------------------------\n",
        "# Funções auxiliares de métricas inline\n",
        "# ---------------------------------------------------------------------------\n",
        "def _acuracia(logits: torch.Tensor, targets: torch.Tensor) -> float:\n",
        "    \"\"\"Acurácia para classificação binária a partir de logits.\"\"\"\n",
        "    preds = (torch.sigmoid(logits) >= 0.5).float()\n",
        "    return (preds == targets).float().mean().item()\n",
        "\n",
        "\n",
        "def _gradient_norm(modelo: nn.Module) -> float:\n",
        "    \"\"\"\n",
        "    Calcula a norma L2 dos gradientes de todos os parâmetros treináveis.\n",
        "    Usado para diagnosticar vanishing/exploding gradients.\n",
        "    \"\"\"\n",
        "    total_norm = 0.0\n",
        "    for p in modelo.parameters():\n",
        "        if p.grad is not None:\n",
        "            total_norm += p.grad.data.norm(2).item() ** 2\n",
        "    return total_norm ** 0.5\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------------------------\n",
        "# Training loop: Classificação\n",
        "# ---------------------------------------------------------------------------\n",
        "def treinar_classificador(\n",
        "    modelo: nn.Module,\n",
        "    loader_treino: DataLoader,\n",
        "    loader_val: DataLoader,\n",
        "    n_epocas: int,\n",
        "    otimizador: torch.optim.Optimizer,\n",
        "    scheduler=None,\n",
        "    device: torch.device = torch.device('cpu'),\n",
        "    writer: Optional[SummaryWriter] = None,\n",
        "    dir_checkpoints: str = 'checkpoints',\n",
        "    nome_experimento: str = 'classif',\n",
        "    paciencia: int = 10,\n",
        ") -> Dict[str, List]:\n",
        "    \"\"\"\n",
        "    Loop de treinamento completo para classificação binária.\n",
        "\n",
        "    Funcionalidades:\n",
        "    - Ciclo de validação por época\n",
        "    - Registro de gradient norms para diagnóstico\n",
        "    - Checkpointing via state_dict (salva melhor modelo)\n",
        "    - Early stopping por val_loss\n",
        "    - Logging no TensorBoard\n",
        "\n",
        "    Retorna\n",
        "    -------\n",
        "    historico : dict\n",
        "        Dicionário com listas de métricas por época:\n",
        "        'train_loss', 'val_loss', 'train_acc', 'val_acc', 'grad_norm', 'lr'\n",
        "    \"\"\"\n",
        "    os.makedirs(dir_checkpoints, exist_ok=True)\n",
        "    caminho_melhor = os.path.join(dir_checkpoints, f'melhor_{nome_experimento}.pt')\n",
        "\n",
        "    criterio = nn.BCEWithLogitsLoss()\n",
        "    modelo = modelo.to(device)\n",
        "\n",
        "    historico = {\n",
        "        'train_loss': [], 'val_loss': [],\n",
        "        'train_acc':  [], 'val_acc':  [],\n",
        "        'grad_norm':  [], 'lr':       []\n",
        "    }\n",
        "\n",
        "    melhor_val_loss = float('inf')\n",
        "    epocas_sem_melhora = 0\n",
        "\n",
        "    print(f\"\\n{'='*65}\")\n",
        "    print(f\"  Treinamento: {nome_experimento}\")\n",
        "    print(f\"  Épocas: {n_epocas} | Device: {device} | Paciência: {paciencia}\")\n",
        "    print(f\"{'='*65}\")\n",
        "    print(f\"{'Época':>6} {'T.Loss':>9} {'V.Loss':>9} {'T.Acc':>8} {'V.Acc':>8} \"\n",
        "          f\"{'GradNorm':>10} {'LR':>10} {'Tempo':>8}\")\n",
        "    print(f\"{'-'*65}\")\n",
        "\n",
        "    for epoca in range(1, n_epocas + 1):\n",
        "        t0 = time.time()\n",
        "\n",
        "        # ── Fase de Treino ────────────────────────────────────────────────\n",
        "        modelo.train()\n",
        "        soma_loss_treino = 0.0\n",
        "        soma_acc_treino = 0.0\n",
        "        soma_grad_norm = 0.0\n",
        "        n_batches = 0\n",
        "\n",
        "        for X_batch, y_batch in loader_treino:\n",
        "            X_batch = X_batch.to(device)\n",
        "            y_batch = y_batch.to(device).unsqueeze(1)  # (N,) → (N,1)\n",
        "\n",
        "            otimizador.zero_grad()\n",
        "            logits = modelo(X_batch)\n",
        "            loss = criterio(logits, y_batch)\n",
        "            loss.backward()\n",
        "\n",
        "            # Registra gradient norm ANTES do step (gradients ainda existem)\n",
        "            soma_grad_norm += _gradient_norm(modelo)\n",
        "\n",
        "            otimizador.step()\n",
        "\n",
        "            soma_loss_treino += loss.item()\n",
        "            soma_acc_treino  += _acuracia(logits.detach(), y_batch)\n",
        "            n_batches += 1\n",
        "\n",
        "        loss_treino  = soma_loss_treino / n_batches\n",
        "        acc_treino   = soma_acc_treino  / n_batches\n",
        "        grad_norm    = soma_grad_norm   / n_batches\n",
        "\n",
        "        # ── Fase de Validação ─────────────────────────────────────────────\n",
        "        modelo.eval()\n",
        "        soma_loss_val = 0.0\n",
        "        soma_acc_val  = 0.0\n",
        "        n_batches_val = 0\n",
        "\n",
        "        with torch.no_grad():\n",
        "            for X_val, y_val in loader_val:\n",
        "                X_val = X_val.to(device)\n",
        "                y_val = y_val.to(device).unsqueeze(1)\n",
        "\n",
        "                logits_val = modelo(X_val)\n",
        "                loss_val   = criterio(logits_val, y_val)\n",
        "\n",
        "                soma_loss_val += loss_val.item()\n",
        "                soma_acc_val  += _acuracia(logits_val, y_val)\n",
        "                n_batches_val += 1\n",
        "\n",
        "        loss_val = soma_loss_val / n_batches_val\n",
        "        acc_val  = soma_acc_val  / n_batches_val\n",
        "\n",
        "        # ── Learning Rate atual ───────────────────────────────────────────\n",
        "        lr_atual = otimizador.param_groups[0]['lr']\n",
        "\n",
        "        # ── Registra no histórico ─────────────────────────────────────────\n",
        "        historico['train_loss'].append(loss_treino)\n",
        "        historico['val_loss'].append(loss_val)\n",
        "        historico['train_acc'].append(acc_treino)\n",
        "        historico['val_acc'].append(acc_val)\n",
        "        historico['grad_norm'].append(grad_norm)\n",
        "        historico['lr'].append(lr_atual)\n",
        "\n",
        "        # ── TensorBoard ───────────────────────────────────────────────────\n",
        "        if writer is not None:\n",
        "            writer.add_scalars('Loss', {'treino': loss_treino, 'val': loss_val}, epoca)\n",
        "            writer.add_scalars('Acuracia', {'treino': acc_treino, 'val': acc_val}, epoca)\n",
        "            writer.add_scalar('Diagnostico/GradientNorm', grad_norm, epoca)\n",
        "            writer.add_scalar('Otimizador/LearningRate', lr_atual, epoca)\n",
        "\n",
        "        # ── Scheduler ────────────────────────────────────────────────────\n",
        "        if scheduler is not None:\n",
        "            # ReduceLROnPlateau precisa do val_loss como argumento\n",
        "            if isinstance(scheduler, torch.optim.lr_scheduler.ReduceLROnPlateau):\n",
        "                scheduler.step(loss_val)\n",
        "            else:\n",
        "                scheduler.step()\n",
        "\n",
        "        # ── Checkpointing ─────────────────────────────────────────────────\n",
        "        if loss_val < melhor_val_loss:\n",
        "            melhor_val_loss = loss_val\n",
        "            epocas_sem_melhora = 0\n",
        "            torch.save({\n",
        "                'epoca':            epoca,\n",
        "                'model_state_dict': modelo.state_dict(),\n",
        "                'optim_state_dict': otimizador.state_dict(),\n",
        "                'val_loss':         loss_val,\n",
        "                'val_acc':          acc_val,\n",
        "                'historico':        historico,\n",
        "            }, caminho_melhor)\n",
        "            marker = ' ✓'\n",
        "        else:\n",
        "            epocas_sem_melhora += 1\n",
        "            marker = ''\n",
        "\n",
        "        tempo = time.time() - t0\n",
        "        print(f\"{epoca:>6} {loss_treino:>9.4f} {loss_val:>9.4f} \"\n",
        "              f\"{acc_treino:>8.4f} {acc_val:>8.4f} \"\n",
        "              f\"{grad_norm:>10.4f} {lr_atual:>10.2e} \"\n",
        "              f\"{tempo:>7.1f}s{marker}\")\n",
        "\n",
        "        # ── Early Stopping ────────────────────────────────────────────────\n",
        "        if epocas_sem_melhora >= paciencia:\n",
        "            print(f\"\\n[Early Stopping] Sem melhora por {paciencia} épocas. \"\n",
        "                  f\"Melhor val_loss: {melhor_val_loss:.4f}\")\n",
        "            break\n",
        "\n",
        "    print(f\"\\n[Checkpointing] Melhor modelo salvo em: {caminho_melhor}\")\n",
        "    return historico\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------------------------\n",
        "# Training loop: Regressão\n",
        "# ---------------------------------------------------------------------------\n",
        "def treinar_regressor(\n",
        "    modelo: nn.Module,\n",
        "    loader_treino: DataLoader,\n",
        "    loader_val: DataLoader,\n",
        "    n_epocas: int,\n",
        "    otimizador: torch.optim.Optimizer,\n",
        "    scheduler=None,\n",
        "    device: torch.device = torch.device('cpu'),\n",
        "    writer: Optional[SummaryWriter] = None,\n",
        "    dir_checkpoints: str = 'checkpoints',\n",
        "    nome_experimento: str = 'regressao',\n",
        "    paciencia: int = 10,\n",
        ") -> Dict[str, List]:\n",
        "    \"\"\"\n",
        "    Loop de treinamento para regressão (predição de int_rate).\n",
        "\n",
        "    Loss: MSELoss\n",
        "    Métricas adicionais calculadas no histórico: MAE (por batch)\n",
        "    \"\"\"\n",
        "    os.makedirs(dir_checkpoints, exist_ok=True)\n",
        "    caminho_melhor = os.path.join(dir_checkpoints, f'melhor_{nome_experimento}.pt')\n",
        "\n",
        "    criterio_mse = nn.MSELoss()\n",
        "    criterio_mae = nn.L1Loss()\n",
        "    modelo = modelo.to(device)\n",
        "\n",
        "    historico = {\n",
        "        'train_mse': [], 'val_mse': [],\n",
        "        'train_mae': [], 'val_mae': [],\n",
        "        'grad_norm': [], 'lr':      []\n",
        "    }\n",
        "\n",
        "    melhor_val_mse = float('inf')\n",
        "    epocas_sem_melhora = 0\n",
        "\n",
        "    print(f\"\\n{'='*65}\")\n",
        "    print(f\"  Regressão: {nome_experimento}\")\n",
        "    print(f\"  Épocas: {n_epocas} | Device: {device} | Paciência: {paciencia}\")\n",
        "    print(f\"{'='*65}\")\n",
        "    print(f\"{'Época':>6} {'T.MSE':>9} {'V.MSE':>9} {'T.MAE':>9} {'V.MAE':>9} \"\n",
        "          f\"{'GradNorm':>10} {'LR':>10}\")\n",
        "    print(f\"{'-'*65}\")\n",
        "\n",
        "    for epoca in range(1, n_epocas + 1):\n",
        "        t0 = time.time()\n",
        "\n",
        "        # ── Fase de Treino ────────────────────────────────────────────────\n",
        "        modelo.train()\n",
        "        soma_mse_t = 0.0\n",
        "        soma_mae_t = 0.0\n",
        "        soma_gn    = 0.0\n",
        "        n_b        = 0\n",
        "\n",
        "        for X_batch, y_batch in loader_treino:\n",
        "            X_batch = X_batch.to(device)\n",
        "            y_batch = y_batch.to(device).unsqueeze(1)\n",
        "\n",
        "            otimizador.zero_grad()\n",
        "            preds = modelo(X_batch)\n",
        "            loss  = criterio_mse(preds, y_batch)\n",
        "            loss.backward()\n",
        "\n",
        "            soma_gn    += _gradient_norm(modelo)\n",
        "            otimizador.step()\n",
        "\n",
        "            soma_mse_t += loss.item()\n",
        "            soma_mae_t += criterio_mae(preds.detach(), y_batch).item()\n",
        "            n_b += 1\n",
        "\n",
        "        mse_t = soma_mse_t / n_b\n",
        "        mae_t = soma_mae_t / n_b\n",
        "        gn    = soma_gn    / n_b\n",
        "\n",
        "        # ── Fase de Validação ─────────────────────────────────────────────\n",
        "        modelo.eval()\n",
        "        soma_mse_v = 0.0\n",
        "        soma_mae_v = 0.0\n",
        "        n_bv       = 0\n",
        "\n",
        "        with torch.no_grad():\n",
        "            for X_val, y_val in loader_val:\n",
        "                X_val = X_val.to(device)\n",
        "                y_val = y_val.to(device).unsqueeze(1)\n",
        "\n",
        "                preds_v = modelo(X_val)\n",
        "                soma_mse_v += criterio_mse(preds_v, y_val).item()\n",
        "                soma_mae_v += criterio_mae(preds_v, y_val).item()\n",
        "                n_bv += 1\n",
        "\n",
        "        mse_v = soma_mse_v / n_bv\n",
        "        mae_v = soma_mae_v / n_bv\n",
        "\n",
        "        lr_atual = otimizador.param_groups[0]['lr']\n",
        "\n",
        "        historico['train_mse'].append(mse_t)\n",
        "        historico['val_mse'].append(mse_v)\n",
        "        historico['train_mae'].append(mae_t)\n",
        "        historico['val_mae'].append(mae_v)\n",
        "        historico['grad_norm'].append(gn)\n",
        "        historico['lr'].append(lr_atual)\n",
        "\n",
        "        if writer is not None:\n",
        "            writer.add_scalars('MSE', {'treino': mse_t, 'val': mse_v}, epoca)\n",
        "            writer.add_scalars('MAE', {'treino': mae_t, 'val': mae_v}, epoca)\n",
        "            writer.add_scalar('Diagnostico/GradientNorm', gn, epoca)\n",
        "            writer.add_scalar('Otimizador/LearningRate', lr_atual, epoca)\n",
        "\n",
        "        if scheduler is not None:\n",
        "            if isinstance(scheduler, torch.optim.lr_scheduler.ReduceLROnPlateau):\n",
        "                scheduler.step(mse_v)\n",
        "            else:\n",
        "                scheduler.step()\n",
        "\n",
        "        if mse_v < melhor_val_mse:\n",
        "            melhor_val_mse = mse_v\n",
        "            epocas_sem_melhora = 0\n",
        "            torch.save({\n",
        "                'epoca':            epoca,\n",
        "                'model_state_dict': modelo.state_dict(),\n",
        "                'optim_state_dict': otimizador.state_dict(),\n",
        "                'val_mse':          mse_v,\n",
        "                'val_mae':          mae_v,\n",
        "                'historico':        historico,\n",
        "            }, caminho_melhor)\n",
        "            marker = ' ✓'\n",
        "        else:\n",
        "            epocas_sem_melhora += 1\n",
        "            marker = ''\n",
        "\n",
        "        tempo = time.time() - t0\n",
        "        print(f\"{epoca:>6} {mse_t:>9.4f} {mse_v:>9.4f} \"\n",
        "              f\"{mae_t:>9.4f} {mae_v:>9.4f} \"\n",
        "              f\"{gn:>10.4f} {lr_atual:>10.2e} \"\n",
        "              f\"{tempo:>7.1f}s{marker}\")\n",
        "\n",
        "        if epocas_sem_melhora >= paciencia:\n",
        "            print(f\"\\n[Early Stopping] Sem melhora por {paciencia} épocas.\")\n",
        "            break\n",
        "\n",
        "    print(f\"\\n[Checkpointing] Melhor modelo salvo em: {caminho_melhor}\")\n",
        "    return historico\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------------------------\n",
        "# Carregamento de checkpoint\n",
        "# ---------------------------------------------------------------------------\n",
        "def carregar_checkpoint(\n",
        "    modelo: nn.Module,\n",
        "    caminho: str,\n",
        "    otimizador: Optional[torch.optim.Optimizer] = None,\n",
        "    device: torch.device = torch.device('cpu'),\n",
        ") -> Dict:\n",
        "    \"\"\"\n",
        "    Recarrega modelo e otimizador a partir de um checkpoint salvo com state_dict.\n",
        "\n",
        "    Permite reproduzir predições exatamente como no ponto salvo.\n",
        "\n",
        "    Parâmetros\n",
        "    ----------\n",
        "    modelo : nn.Module\n",
        "        Modelo com a mesma arquitetura do checkpoint.\n",
        "    caminho : str\n",
        "        Caminho para o arquivo .pt salvo pelo treinar_*.\n",
        "    otimizador : Optimizer ou None\n",
        "        Se fornecido, restaura também o estado do otimizador.\n",
        "    device : torch.device\n",
        "        Device de destino.\n",
        "\n",
        "    Retorna\n",
        "    -------\n",
        "    checkpoint : dict\n",
        "        Dicionário com todos os campos salvos (época, métricas, histórico).\n",
        "    \"\"\"\n",
        "    checkpoint = torch.load(caminho, map_location=device)\n",
        "    modelo.load_state_dict(checkpoint['model_state_dict'])\n",
        "    modelo.to(device)\n",
        "    modelo.eval()\n",
        "\n",
        "    if otimizador is not None and 'optim_state_dict' in checkpoint:\n",
        "        otimizador.load_state_dict(checkpoint['optim_state_dict'])\n",
        "\n",
        "    epoca = checkpoint.get('epoca', '?')\n",
        "    print(f\"[Checkpoint] Modelo carregado — época {epoca} | \"\n",
        "          f\"arquivo: {caminho}\")\n",
        "    return checkpoint\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------------------------\n",
        "# Inferência em lote (reprodução de predições)\n",
        "# ---------------------------------------------------------------------------\n",
        "@torch.no_grad()\n",
        "def predizer_classificador(\n",
        "    modelo: nn.Module,\n",
        "    loader: DataLoader,\n",
        "    device: torch.device = torch.device('cpu'),\n",
        "    threshold: float = 0.5,\n",
        ") -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:\n",
        "    \"\"\"\n",
        "    Gera predições para todo o DataLoader.\n",
        "\n",
        "    Retorna\n",
        "    -------\n",
        "    todas_probs   : tensor de probabilidades (sigmoid aplicado)\n",
        "    todas_preds   : tensor de classes preditas (0 ou 1)\n",
        "    todos_targets : tensor de labels verdadeiros\n",
        "    \"\"\"\n",
        "    modelo.eval()\n",
        "    modelo.to(device)\n",
        "\n",
        "    lista_probs   = []\n",
        "    lista_preds   = []\n",
        "    lista_targets = []\n",
        "\n",
        "    for X_batch, y_batch in loader:\n",
        "        X_batch = X_batch.to(device)\n",
        "        logits  = modelo(X_batch)\n",
        "        probs   = torch.sigmoid(logits).squeeze(1)\n",
        "        preds   = (probs >= threshold).float()\n",
        "\n",
        "        lista_probs.append(probs.cpu())\n",
        "        lista_preds.append(preds.cpu())\n",
        "        lista_targets.append(y_batch.cpu())\n",
        "\n",
        "    return (torch.cat(lista_probs),\n",
        "            torch.cat(lista_preds),\n",
        "            torch.cat(lista_targets))\n",
        "\n",
        "\n",
        "@torch.no_grad()\n",
        "def predizer_regressor(\n",
        "    modelo: nn.Module,\n",
        "    loader: DataLoader,\n",
        "    device: torch.device = torch.device('cpu'),\n",
        ") -> Tuple[torch.Tensor, torch.Tensor]:\n",
        "    \"\"\"\n",
        "    Gera predições de regressão para todo o DataLoader.\n",
        "\n",
        "    Retorna\n",
        "    -------\n",
        "    todas_preds   : tensor de valores preditos\n",
        "    todos_targets : tensor de valores reais\n",
        "    \"\"\"\n",
        "    modelo.eval()\n",
        "    modelo.to(device)\n",
        "\n",
        "    lista_preds   = []\n",
        "    lista_targets = []\n",
        "\n",
        "    for X_batch, y_batch in loader:\n",
        "        X_batch = X_batch.to(device)\n",
        "        preds   = modelo(X_batch).squeeze(1)\n",
        "\n",
        "        lista_preds.append(preds.cpu())\n",
        "        lista_targets.append(y_batch.cpu())\n",
        "\n",
        "    return torch.cat(lista_preds), torch.cat(lista_targets)\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "9AJah7g_yxZS",
        "outputId": "5d2e6260-786d-4467-8157-c8c5552ad822"
      },
      "execution_count": 7,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Overwriting src/training.py\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "%%writefile src/utils.py\n",
        "\n",
        "\"\"\"\n",
        "utils.py — Métricas, visualizações e helpers para o Pipeline MLP.\n",
        "Dataset: Lending Club (Kaggle)\n",
        "Autor: MBA Engenharia de IA\n",
        "\"\"\"\n",
        "\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import matplotlib.gridspec as gridspec\n",
        "import seaborn as sns\n",
        "import torch\n",
        "from sklearn.metrics import (\n",
        "    confusion_matrix, classification_report,\n",
        "    roc_auc_score, roc_curve, precision_recall_curve,\n",
        "    average_precision_score\n",
        ")\n",
        "from typing import Dict, List, Optional\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------------------------\n",
        "# Paleta e estilo padrão\n",
        "# ---------------------------------------------------------------------------\n",
        "CORES = {\n",
        "    'treino':    '#2196F3',   # azul\n",
        "    'val':       '#FF9800',   # laranja\n",
        "    'teste':     '#4CAF50',   # verde\n",
        "    'baseline':  '#9E9E9E',   # cinza\n",
        "    'destaque':  '#F44336',   # vermelho\n",
        "    'positivo':  '#E91E63',   # rosa\n",
        "    'negativo':  '#3F51B5',   # azul escuro\n",
        "}\n",
        "\n",
        "def _estilo():\n",
        "    \"\"\"Aplica estilo consistente a todos os gráficos.\"\"\"\n",
        "    plt.rcParams.update({\n",
        "        'figure.facecolor': 'white',\n",
        "        'axes.facecolor':   '#F9F9F9',\n",
        "        'axes.grid':        True,\n",
        "        'grid.alpha':       0.4,\n",
        "        'font.size':        11,\n",
        "        'axes.titlesize':   13,\n",
        "        'axes.labelsize':   11,\n",
        "    })\n",
        "\n",
        "_estilo()\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------------------------\n",
        "# Métricas de Regressão\n",
        "# ---------------------------------------------------------------------------\n",
        "def calcular_metricas_regressao(\n",
        "    y_true: torch.Tensor,\n",
        "    y_pred: torch.Tensor,\n",
        ") -> Dict[str, float]:\n",
        "    \"\"\"\n",
        "    Calcula MAE, RMSE e R² para o conjunto de teste.\n",
        "\n",
        "    Parâmetros\n",
        "    ----------\n",
        "    y_true : tensor com valores reais\n",
        "    y_pred : tensor com valores preditos\n",
        "\n",
        "    Retorna\n",
        "    -------\n",
        "    dict com 'MAE', 'RMSE', 'R2'\n",
        "    \"\"\"\n",
        "    y_true = y_true.numpy().flatten()\n",
        "    y_pred = y_pred.numpy().flatten()\n",
        "\n",
        "    mae  = np.mean(np.abs(y_true - y_pred))\n",
        "    mse  = np.mean((y_true - y_pred) ** 2)\n",
        "    rmse = np.sqrt(mse)\n",
        "\n",
        "    ss_res = np.sum((y_true - y_pred) ** 2)\n",
        "    ss_tot = np.sum((y_true - np.mean(y_true)) ** 2)\n",
        "    r2 = 1 - (ss_res / ss_tot) if ss_tot > 0 else 0.0\n",
        "\n",
        "    return {'MAE': mae, 'RMSE': rmse, 'R2': r2, 'MSE': mse}\n",
        "\n",
        "\n",
        "def imprimir_metricas_regressao(metricas: Dict[str, float],\n",
        "                                 nome: str = 'Teste') -> None:\n",
        "    \"\"\"Imprime tabela formatada das métricas de regressão.\"\"\"\n",
        "    print(f\"\\n{'='*40}\")\n",
        "    print(f\"  Métricas de Regressão — {nome}\")\n",
        "    print(f\"{'='*40}\")\n",
        "    print(f\"  MSE  : {metricas['MSE']:.6f}\")\n",
        "    print(f\"  RMSE : {metricas['RMSE']:.6f}\")\n",
        "    print(f\"  MAE  : {metricas['MAE']:.6f}\")\n",
        "    print(f\"  R²   : {metricas['R2']:.6f}\")\n",
        "    print(f\"{'='*40}\\n\")\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------------------------\n",
        "# Métricas de Classificação\n",
        "# ---------------------------------------------------------------------------\n",
        "def calcular_metricas_classificacao(\n",
        "    y_true: torch.Tensor,\n",
        "    y_pred: torch.Tensor,\n",
        "    y_prob: torch.Tensor,\n",
        ") -> Dict[str, float]:\n",
        "    \"\"\"\n",
        "    Calcula métricas completas para classificação binária.\n",
        "\n",
        "    Retorna dict com acuracia, auc_roc, avg_precision e report.\n",
        "    \"\"\"\n",
        "    yt = y_true.numpy().flatten().astype(int)\n",
        "    yp = y_pred.numpy().flatten().astype(int)\n",
        "    yprob = y_prob.numpy().flatten()\n",
        "\n",
        "    auc   = roc_auc_score(yt, yprob)\n",
        "    ap    = average_precision_score(yt, yprob)\n",
        "    acc   = (yt == yp).mean()\n",
        "    rep   = classification_report(yt, yp,\n",
        "                                   target_names=['Fully Paid', 'Charged Off'])\n",
        "\n",
        "    return {\n",
        "        'acuracia':       acc,\n",
        "        'auc_roc':        auc,\n",
        "        'avg_precision':  ap,\n",
        "        'report':         rep,\n",
        "    }\n",
        "\n",
        "\n",
        "def imprimir_metricas_classificacao(metricas: Dict) -> None:\n",
        "    \"\"\"Imprime tabela formatada das métricas de classificação.\"\"\"\n",
        "    print(f\"\\n{'='*50}\")\n",
        "    print(f\"  Métricas de Classificação — Conjunto de Teste\")\n",
        "    print(f\"{'='*50}\")\n",
        "    print(f\"  Acurácia       : {metricas['acuracia']:.4f}\")\n",
        "    print(f\"  AUC-ROC        : {metricas['auc_roc']:.4f}\")\n",
        "    print(f\"  Avg Precision  : {metricas['avg_precision']:.4f}\")\n",
        "    print(f\"\\n{metricas['report']}\")\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------------------------\n",
        "# Plot: Curvas de Loss (treino vs validação)\n",
        "# ---------------------------------------------------------------------------\n",
        "def plotar_curvas_loss(\n",
        "    historico: Dict[str, List],\n",
        "    titulo: str = 'Curvas de Loss',\n",
        "    chave_treino: str = 'train_loss',\n",
        "    chave_val: str = 'val_loss',\n",
        "    fenomeno: Optional[str] = None,\n",
        ") -> None:\n",
        "    \"\"\"\n",
        "    Plota curvas de loss com nome explícito do fenômeno observado.\n",
        "\n",
        "    Parâmetros\n",
        "    ----------\n",
        "    historico : dict retornado pelo training loop\n",
        "    titulo : título do gráfico\n",
        "    fenomeno : str — ex: 'Overfitting', 'Underfitting', 'Convergência estável'\n",
        "               Será anotado no gráfico.\n",
        "    \"\"\"\n",
        "    fig, ax = plt.subplots(figsize=(10, 5))\n",
        "\n",
        "    epocas = range(1, len(historico[chave_treino]) + 1)\n",
        "    ax.plot(epocas, historico[chave_treino],\n",
        "            color=CORES['treino'], linewidth=2, label='Treino')\n",
        "    ax.plot(epocas, historico[chave_val],\n",
        "            color=CORES['val'],    linewidth=2, label='Validação', linestyle='--')\n",
        "\n",
        "    # Marca época do melhor val_loss\n",
        "    melhor_ep = int(np.argmin(historico[chave_val])) + 1\n",
        "    melhor_v  = min(historico[chave_val])\n",
        "    ax.axvline(melhor_ep, color=CORES['destaque'],\n",
        "               linestyle=':', linewidth=1.5,\n",
        "               label=f'Melhor val (época {melhor_ep})')\n",
        "    ax.scatter([melhor_ep], [melhor_v],\n",
        "               color=CORES['destaque'], zorder=5, s=60)\n",
        "\n",
        "    # Anotação do fenômeno observado\n",
        "    if fenomeno:\n",
        "        ax.text(0.98, 0.95, f'Fenômeno: {fenomeno}',\n",
        "                transform=ax.transAxes, ha='right', va='top',\n",
        "                fontsize=11, style='italic',\n",
        "                bbox=dict(boxstyle='round,pad=0.3',\n",
        "                          facecolor='#FFF9C4', alpha=0.8))\n",
        "\n",
        "    ax.set_title(titulo)\n",
        "    ax.set_xlabel('Época')\n",
        "    ax.set_ylabel('Loss')\n",
        "    ax.legend()\n",
        "    plt.tight_layout()\n",
        "    plt.show()\n",
        "\n",
        "\n",
        "def plotar_curvas_comparativas(\n",
        "    historicos: Dict[str, Dict],\n",
        "    chave: str = 'val_loss',\n",
        "    titulo: str = 'Comparação — Validação Loss',\n",
        "    ylabel: str = 'Val Loss',\n",
        ") -> None:\n",
        "    \"\"\"\n",
        "    Plota val_loss (ou outra métrica) de múltiplos experimentos no mesmo gráfico.\n",
        "    Útil para comparar ativações, inicializações, etc.\n",
        "    \"\"\"\n",
        "    fig, ax = plt.subplots(figsize=(11, 5))\n",
        "    cores_ciclo = plt.cm.tab10.colors\n",
        "\n",
        "    for i, (nome, hist) in enumerate(historicos.items()):\n",
        "        if chave in hist:\n",
        "            vals   = hist[chave]\n",
        "            epocas = range(1, len(vals) + 1)\n",
        "            ax.plot(epocas, vals, label=nome,\n",
        "                    color=cores_ciclo[i % 10], linewidth=2)\n",
        "\n",
        "    ax.set_title(titulo)\n",
        "    ax.set_xlabel('Época')\n",
        "    ax.set_ylabel(ylabel)\n",
        "    ax.legend(loc='upper right')\n",
        "    plt.tight_layout()\n",
        "    plt.show()\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------------------------\n",
        "# Plot: Gradient Norm ao longo do treino\n",
        "# ---------------------------------------------------------------------------\n",
        "def plotar_gradient_norm(\n",
        "    historico: Dict[str, List],\n",
        "    titulo: str = 'Norma dos Gradientes por Época',\n",
        ") -> None:\n",
        "    \"\"\"\n",
        "    Plota a evolução da norma dos gradientes.\n",
        "    Permite diagnosticar vanishing (<< 0.01) ou exploding (>> 10) gradients.\n",
        "    \"\"\"\n",
        "    fig, ax = plt.subplots(figsize=(10, 4))\n",
        "    gn = historico['grad_norm']\n",
        "    epocas = range(1, len(gn) + 1)\n",
        "\n",
        "    ax.plot(epocas, gn, color=CORES['destaque'], linewidth=1.8)\n",
        "    ax.axhline(0.01, color='gray', linestyle=':', linewidth=1.2,\n",
        "               label='Limite inferior (vanishing ≈ 0.01)')\n",
        "    ax.axhline(10.0, color='black', linestyle=':', linewidth=1.2,\n",
        "               label='Limite superior (exploding ≈ 10)')\n",
        "\n",
        "    ax.set_title(titulo)\n",
        "    ax.set_xlabel('Época')\n",
        "    ax.set_ylabel('Norma L2 dos Gradientes')\n",
        "    ax.set_yscale('log')\n",
        "    ax.legend()\n",
        "    plt.tight_layout()\n",
        "    plt.show()\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------------------------\n",
        "# Plot: Matriz de Confusão\n",
        "# ---------------------------------------------------------------------------\n",
        "def plotar_matriz_confusao(\n",
        "    y_true: torch.Tensor,\n",
        "    y_pred: torch.Tensor,\n",
        "    classes: List[str] = None,\n",
        "    titulo: str = 'Matriz de Confusão — Conjunto de Teste',\n",
        "    hipotese_erros: Optional[str] = None,\n",
        ") -> None:\n",
        "    \"\"\"\n",
        "    Plota matriz de confusão normalizada e absoluta lado a lado.\n",
        "\n",
        "    Parâmetros\n",
        "    ----------\n",
        "    hipotese_erros : str\n",
        "        Hipótese sobre os padrões de erro observados, anotada no gráfico.\n",
        "    \"\"\"\n",
        "    if classes is None:\n",
        "        classes = ['Fully Paid (0)', 'Charged Off (1)']\n",
        "\n",
        "    yt = y_true.numpy().flatten().astype(int)\n",
        "    yp = y_pred.numpy().flatten().astype(int)\n",
        "\n",
        "    cm     = confusion_matrix(yt, yp)\n",
        "    cm_norm = confusion_matrix(yt, yp, normalize='true')\n",
        "\n",
        "    fig, axes = plt.subplots(1, 2, figsize=(13, 5))\n",
        "    fig.suptitle(titulo, fontsize=14, fontweight='bold')\n",
        "\n",
        "    # Absoluta\n",
        "    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',\n",
        "                xticklabels=classes, yticklabels=classes,\n",
        "                ax=axes[0], cbar=False)\n",
        "    axes[0].set_title('Contagem Absoluta')\n",
        "    axes[0].set_ylabel('Real')\n",
        "    axes[0].set_xlabel('Predito')\n",
        "\n",
        "    # Normalizada\n",
        "    sns.heatmap(cm_norm, annot=True, fmt='.2%', cmap='Blues',\n",
        "                xticklabels=classes, yticklabels=classes,\n",
        "                ax=axes[1], cbar=False)\n",
        "    axes[1].set_title('Normalizada por Classe Real')\n",
        "    axes[1].set_ylabel('Real')\n",
        "    axes[1].set_xlabel('Predito')\n",
        "\n",
        "    if hipotese_erros:\n",
        "        fig.text(0.5, -0.04, f'Hipótese sobre erros: {hipotese_erros}',\n",
        "                 ha='center', fontsize=10, style='italic',\n",
        "                 bbox=dict(boxstyle='round,pad=0.3',\n",
        "                           facecolor='#E3F2FD', alpha=0.8))\n",
        "\n",
        "    plt.tight_layout()\n",
        "    plt.show()\n",
        "\n",
        "    # Imprime TN, FP, FN, TP explicitamente\n",
        "    tn, fp, fn, tp = cm.ravel()\n",
        "    print(f\"\\n  Verdadeiro Negativo (TN) : {tn:,}  — Fully Paid previsto corretamente\")\n",
        "    print(f\"  Falso Positivo      (FP) : {fp:,}  — Fully Paid previsto como Charged Off\")\n",
        "    print(f\"  Falso Negativo      (FN) : {fn:,}  — Charged Off previsto como Fully Paid\")\n",
        "    print(f\"  Verdadeiro Positivo (TP) : {tp:,}  — Charged Off previsto corretamente\")\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------------------------\n",
        "# Plot: Curva ROC e Precision-Recall\n",
        "# ---------------------------------------------------------------------------\n",
        "def plotar_roc_pr(\n",
        "    y_true: torch.Tensor,\n",
        "    y_prob: torch.Tensor,\n",
        "    titulo: str = 'Curvas ROC e Precision-Recall — Teste',\n",
        ") -> None:\n",
        "    \"\"\"Plota curva ROC e curva Precision-Recall lado a lado.\"\"\"\n",
        "    yt    = y_true.numpy().flatten().astype(int)\n",
        "    yprob = y_prob.numpy().flatten()\n",
        "\n",
        "    fpr, tpr, _  = roc_curve(yt, yprob)\n",
        "    auc_val       = roc_auc_score(yt, yprob)\n",
        "    prec, rec, _  = precision_recall_curve(yt, yprob)\n",
        "    ap            = average_precision_score(yt, yprob)\n",
        "\n",
        "    fig, axes = plt.subplots(1, 2, figsize=(13, 5))\n",
        "    fig.suptitle(titulo, fontsize=13)\n",
        "\n",
        "    # ROC\n",
        "    axes[0].plot(fpr, tpr, color=CORES['treino'], lw=2,\n",
        "                 label=f'AUC = {auc_val:.4f}')\n",
        "    axes[0].plot([0, 1], [0, 1], 'k--', lw=1, label='Baseline aleatório')\n",
        "    axes[0].set_xlabel('Taxa de Falso Positivo')\n",
        "    axes[0].set_ylabel('Taxa de Verdadeiro Positivo')\n",
        "    axes[0].set_title('Curva ROC')\n",
        "    axes[0].legend()\n",
        "\n",
        "    # PR\n",
        "    axes[1].plot(rec, prec, color=CORES['val'], lw=2,\n",
        "                 label=f'AP = {ap:.4f}')\n",
        "    axes[1].set_xlabel('Recall')\n",
        "    axes[1].set_ylabel('Precisão')\n",
        "    axes[1].set_title('Curva Precision-Recall')\n",
        "    axes[1].legend()\n",
        "\n",
        "    plt.tight_layout()\n",
        "    plt.show()\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------------------------\n",
        "# Plot: Distribuição de Ativações\n",
        "# ---------------------------------------------------------------------------\n",
        "def plotar_distribuicao_ativacoes(\n",
        "    modelo: torch.nn.Module,\n",
        "    X_amostra: torch.Tensor,\n",
        "    device: torch.device = torch.device('cpu'),\n",
        "    titulo: str = 'Distribuição das Ativações por Camada',\n",
        ") -> None:\n",
        "    \"\"\"\n",
        "    Passa uma amostra pela rede e plota histograma das ativações\n",
        "    de cada camada oculta.\n",
        "\n",
        "    Útil para detectar saturação (tanh/sigmoid) ou neurônios mortos (ReLU).\n",
        "    \"\"\"\n",
        "    modelo.eval()\n",
        "    modelo.to(device)\n",
        "    X = X_amostra.to(device)\n",
        "\n",
        "    ativacoes = {}\n",
        "    hooks = []\n",
        "\n",
        "    def _hook(nome):\n",
        "        def fn(module, input, output):\n",
        "            ativacoes[nome] = output.detach().cpu()\n",
        "        return fn\n",
        "\n",
        "    # Registra hooks apenas nas camadas de ativação\n",
        "    for nome, modulo in modelo.named_modules():\n",
        "        if isinstance(modulo, (torch.nn.ReLU, torch.nn.Tanh,\n",
        "                               torch.nn.LeakyReLU, torch.nn.ELU,\n",
        "                               torch.nn.SELU)):\n",
        "            hooks.append(modulo.register_forward_hook(_hook(nome)))\n",
        "\n",
        "    with torch.no_grad():\n",
        "        modelo(X)\n",
        "\n",
        "    for h in hooks:\n",
        "        h.remove()\n",
        "\n",
        "    n = len(ativacoes)\n",
        "    if n == 0:\n",
        "        print(\"[Aviso] Nenhuma ativação capturada. Verifique a arquitetura.\")\n",
        "        return\n",
        "\n",
        "    fig, axes = plt.subplots(1, n, figsize=(4 * n, 4))\n",
        "    if n == 1:\n",
        "        axes = [axes]\n",
        "\n",
        "    fig.suptitle(titulo, fontsize=13)\n",
        "\n",
        "    for ax, (nome, ativ) in zip(axes, ativacoes.items()):\n",
        "        vals = ativ.numpy().flatten()\n",
        "        ax.hist(vals, bins=80, color=CORES['treino'], alpha=0.7, edgecolor='none')\n",
        "        ax.axvline(0, color=CORES['destaque'], linestyle='--', linewidth=1)\n",
        "        ax.set_title(f'{nome}\\nmean={vals.mean():.3f} std={vals.std():.3f}')\n",
        "        ax.set_xlabel('Valor de ativação')\n",
        "        ax.set_ylabel('Frequência')\n",
        "\n",
        "    plt.tight_layout()\n",
        "    plt.show()\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------------------------\n",
        "# Plot: Predições vs Real (Regressão)\n",
        "# ---------------------------------------------------------------------------\n",
        "def plotar_pred_vs_real(\n",
        "    y_true: torch.Tensor,\n",
        "    y_pred: torch.Tensor,\n",
        "    metricas: Dict[str, float],\n",
        "    titulo: str = 'Predições vs Valores Reais — int_rate',\n",
        "    max_amostras: int = 5000,\n",
        ") -> None:\n",
        "    \"\"\"Scatter plot de predições vs valores reais para regressão.\"\"\"\n",
        "    yt = y_true.numpy().flatten()\n",
        "    yp = y_pred.numpy().flatten()\n",
        "\n",
        "    # Amostragem para não sobrecarregar o scatter\n",
        "    if len(yt) > max_amostras:\n",
        "        idx = np.random.choice(len(yt), max_amostras, replace=False)\n",
        "        yt  = yt[idx]\n",
        "        yp  = yp[idx]\n",
        "\n",
        "    fig, axes = plt.subplots(1, 2, figsize=(13, 5))\n",
        "    fig.suptitle(titulo, fontsize=13)\n",
        "\n",
        "    # Scatter\n",
        "    axes[0].scatter(yt, yp, alpha=0.3, s=8, color=CORES['treino'])\n",
        "    lim_min = min(yt.min(), yp.min())\n",
        "    lim_max = max(yt.max(), yp.max())\n",
        "    axes[0].plot([lim_min, lim_max], [lim_min, lim_max],\n",
        "                 'r--', linewidth=1.5, label='Ideal')\n",
        "    axes[0].set_xlabel('int_rate real')\n",
        "    axes[0].set_ylabel('int_rate predito')\n",
        "    axes[0].set_title(f\"RMSE={metricas['RMSE']:.4f}  R²={metricas['R2']:.4f}\")\n",
        "    axes[0].legend()\n",
        "\n",
        "    # Histograma dos resíduos\n",
        "    residuos = yt - yp\n",
        "    axes[1].hist(residuos, bins=80, color=CORES['val'], edgecolor='none', alpha=0.8)\n",
        "    axes[1].axvline(0, color=CORES['destaque'], linestyle='--', linewidth=1.5)\n",
        "    axes[1].set_xlabel('Resíduo (real − predito)')\n",
        "    axes[1].set_ylabel('Frequência')\n",
        "    axes[1].set_title(f\"Distribuição dos Resíduos\\nMAE={metricas['MAE']:.4f}\")\n",
        "\n",
        "    plt.tight_layout()\n",
        "    plt.show()\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------------------------\n",
        "# Baseline não trivial: Regressão e Classificação\n",
        "# ---------------------------------------------------------------------------\n",
        "def baseline_regressao(y_train: np.ndarray, y_test: np.ndarray) -> Dict[str, float]:\n",
        "    \"\"\"\n",
        "    Baseline para regressão: prevê a mediana do conjunto de treino.\n",
        "    (Mais robusto que a média por ser resistente a outliers.)\n",
        "    \"\"\"\n",
        "    mediana = np.median(y_train)\n",
        "    preds = np.full_like(y_test, fill_value=mediana)\n",
        "\n",
        "    mae  = np.mean(np.abs(y_test - preds))\n",
        "    mse  = np.mean((y_test - preds) ** 2)\n",
        "    rmse = np.sqrt(mse)\n",
        "    ss_res = np.sum((y_test - preds) ** 2)\n",
        "    ss_tot = np.sum((y_test - np.mean(y_train)) ** 2)\n",
        "    r2 = 1 - (ss_res / ss_tot) if ss_tot > 0 else 0.0\n",
        "\n",
        "    print(f\"\\n[Baseline Regressão] Prediz mediana do treino: {mediana:.4f}\")\n",
        "    print(f\"  MSE={mse:.6f}  RMSE={rmse:.6f}  MAE={mae:.6f}  R²={r2:.6f}\")\n",
        "    return {'mediana': mediana, 'MAE': mae, 'RMSE': rmse, 'R2': r2, 'MSE': mse}\n",
        "\n",
        "\n",
        "def baseline_classificacao(y_train: np.ndarray, y_test: np.ndarray) -> Dict[str, float]:\n",
        "    \"\"\"\n",
        "    Baseline para classificação: prevê sempre a classe majoritária do treino.\n",
        "    Mais informativo que acurácia aleatória para datasets desbalanceados.\n",
        "    \"\"\"\n",
        "    from collections import Counter\n",
        "    contagem = Counter(y_train)\n",
        "    classe_majoritaria = contagem.most_common(1)[0][0]\n",
        "    preds = np.full_like(y_test, fill_value=classe_majoritaria)\n",
        "\n",
        "    acc = (preds == y_test).mean()\n",
        "    prop = contagem[classe_majoritaria] / len(y_train)\n",
        "\n",
        "    print(f\"\\n[Baseline Classificação] Prevê sempre classe {classe_majoritaria} \"\n",
        "          f\"({prop:.1%} do treino)\")\n",
        "    print(f\"  Acurácia no teste: {acc:.4f}\")\n",
        "    return {'classe_majoritaria': classe_majoritaria, 'acuracia': acc, 'proporcao': prop}\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------------------------\n",
        "# Helper: resumo de hiperparâmetros de um experimento\n",
        "# ---------------------------------------------------------------------------\n",
        "def imprimir_config_experimento(config: Dict) -> None:\n",
        "    \"\"\"Imprime tabela formatada de hiperparâmetros.\"\"\"\n",
        "    print(f\"\\n{'='*45}\")\n",
        "    print(f\"  Configuração do Experimento\")\n",
        "    print(f\"{'='*45}\")\n",
        "    for k, v in config.items():\n",
        "        print(f\"  {k:<25}: {v}\")\n",
        "    print(f\"{'='*45}\\n\")\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "QEa70A8py2aD",
        "outputId": "7fcd1b43-03fa-44c5-c8cf-3cc6ca83a63e"
      },
      "execution_count": 4,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Writing src/utils.py\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "xMV7c0Owy85n"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}